#!/bin/sh
# Build a d_cosim shared library from Verilog source, using Verilator.
#
# Replaces ngspice's shipped `vlnggen` script, which CANNOT WORK on ngspice-46:
# in script-file mode (`ngspice vlnggen foo.v`) the interpreter lowercases every
# literal token on the line — measured 2026-08-08:
#
#     $ printf '*ng_script\necho BARE_UPPER\nsetcs v="X_UPPER"\necho $v\n' > s
#     $ ngspice s
#     bare_upper
#     x_upper                      <- even setcs values are downcased
#
# while the same commands typed interactively keep their case. vlnggen depends on
# case in at least four places (`--Mdir`, `--prefix Vlng`, the `VL_IN`/`VL_OUT`/
# `VL_INOUT` header scan, and the `VL_DATA(...)` lines it echoes), so it fails at
# the first verilator call with
#     %Error: Invalid option: --mdir... Suggested alternative: '-Mdir'
#
# This script performs the same four steps directly. See
# doc/claude/specs/mixed_signal_signal_browser.md §A.
#
# usage: build_cosim_so.sh [-o OUTDIR] [-t] [-V] SOURCE.v [extra verilator args...]
#   -o OUTDIR   where SOURCE.so (and the obj dir) are written; default: cwd
#   -t          --timing build (defines WITH_TIMING in the shim)
#   -V          --trace build: the shim writes a VCD of the design's INTERNALS.
#               Needs the patched shim, so it forces NGSPICE_COSIM_SRC to the
#               in-repo tools/cosim/src unless the caller already set it. Name
#               the output file with the .model card's sim_args, e.g.
#                 .model counter d_cosim simulation="./counter.so" \
#                        sim_args=["counter.vcd"]
set -e

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PREFIX=Vlng
outdir=$(pwd)
timing=0
trace=0

while [ $# -gt 0 ]; do
  case "$1" in
    -o) outdir=$2; shift 2 ;;
    -t) timing=1; shift ;;
    -V) trace=1; shift ;;
    --) shift; break ;;
    *)  break ;;
  esac
done

if [ "$trace" = 1 ]; then
  SHIMDIR=${NGSPICE_COSIM_SRC:-$here/src}
else
  SHIMDIR=${NGSPICE_COSIM_SRC:-/usr/local/share/ngspice/scripts/src}
fi

[ $# -ge 1 ] || { echo "usage: $0 [-o OUTDIR] [-t] SOURCE.v [verilator args...]" >&2; exit 2; }
src=$1; shift
[ -f "$src" ] || { echo "$0: no such file: $src" >&2; exit 1; }
[ -f "$SHIMDIR/verilator_shim.cpp" ] || {
  echo "$0: verilator_shim.cpp not found under $SHIMDIR (set NGSPICE_COSIM_SRC)" >&2; exit 1; }
[ -f "$SHIMDIR/ngspice/cmtypes.h" ] || {
  echo "$0: $SHIMDIR/ngspice/cmtypes.h missing — wrong SHIMDIR" >&2; exit 1; }

command -v verilator >/dev/null || { echo "$0: verilator not installed" >&2; exit 1; }

base=$(basename "$src" .v)
mkdir -p "$outdir"
outdir=$(cd "$outdir" && pwd)
src=$(cd "$(dirname "$src")" && pwd)/$(basename "$src")
objdir=$outdir/${base}_obj_dir
soname=$outdir/$base.so

cflags="--CFLAGS -fpic --CFLAGS -I$SHIMDIR"
[ "$timing" = 1 ] && cflags="$cflags --CFLAGS -DWITH_TIMING --timing"
[ "$trace"  = 1 ] && cflags="$cflags --trace"

# 1. Verilog -> C++, so Vlng.h exists to be scanned for the port list.
verilator --Mdir "$objdir" --prefix $PREFIX $cflags --cc "$src" "$@"

# 2. Port tables. Vlng.h declares each top-level port as
#       VL_IN8(&clk,0,0);   VL_OUT8(&count,3,0);   VL_INOUT8(&io,0,0);
#    and the shim's inputs.h / outputs.h / inouts.h feed those to its VL_DATA
#    macro, which it redefines several times. ORDER IS THE WIRE PROTOCOL: the
#    d_cosim port index the caller passes to in_fn/out_fn is an offset into
#    these tables, so the file order must match Vlng.h's declaration order,
#    which is the order of the module's port list.
#    `VL_IN\([0-9]\+\)` cannot match VL_INOUT: the digits are mandatory and
#    VL_INOUT has a letter there. Same for VL_OUT.
hdr=$objdir/$PREFIX.h
gen() { # gen <VL_ tag> <outfile>
  echo "/* Generated by build_cosim_so.sh: do not edit. */" > "$2"
  sed -n "s/^[[:space:]]*$1\\([0-9]\\+\\)(&\\(.*\\);/VL_DATA(\\1,\\2/p" "$hdr" >> "$2"
}
gen VL_IN    "$objdir/inputs.h"
gen VL_OUT   "$objdir/outputs.h"
gen VL_INOUT "$objdir/inouts.h"

echo "--- ports found ---"
grep -h VL_DATA "$objdir/inputs.h"  | sed 's/^/  in    /' || true
grep -h VL_DATA "$objdir/outputs.h" | sed 's/^/  out   /' || true
grep -h VL_DATA "$objdir/inouts.h"  | sed 's/^/  inout /' || true

# 3. Compile everything, including the shim. Verilator only compiles when asked
#    to build an executable, hence verilator_main.cpp tagging along.
verilator --Mdir "$objdir" --prefix $PREFIX $cflags --cc --build --exe \
    "$SHIMDIR/verilator_main.cpp" "$SHIMDIR/verilator_shim.cpp" "$src" "$@"

# 4. Link the shared library. verilated_timing.o only exists in a --timing build.
objs="$objdir/verilator_shim.o $objdir/verilated.o $objdir/verilated_threads.o"
[ -f "$objdir/verilated_timing.o" ] && objs="$objs $objdir/verilated_timing.o"
# --trace builds emit verilated_vcd_c.o as a GLOBAL object, not inside
# ${PREFIX}__ALL.a — vlnggen's hardcoded object list omits it and fails to link.
[ -f "$objdir/verilated_vcd_c.o" ] && objs="$objs $objdir/verilated_vcd_c.o"
[ -f "$objdir/verilated_threads.o" ] || objs=$(echo "$objs" | sed "s|$objdir/verilated_threads.o||")

g++ --shared $objs "$objdir/${PREFIX}__ALL.a" -pthread -lpthread -o "$soname"
echo "built: $soname"
