# test_sim_profiles.tcl — simulator PROFILES: the model, the persistence and the
# ASE-L state key. Casemode batch item 6; PLAN.md section 3b item 6;
# DECISIONS.md B1 (+ A1's detected/requested split and A2's per-profile `-n`).
# Spec: doc/claude/specs/simulator_profiles.md.
#
# WHAT THIS ITEM IS. xschem already HAS a simulator configuration system: the
# `sim()` array, the `simconf` dialog, `$USER_CONF_DIR/simrc`, and any rc that
# sets the same globals. B1 overturned the plan's brand-new registry file
# ($USER_CONF_DIR/ase_simulators) and ruled that the case mode rides on THAT.
# So every `sim($tool,$i,...)` row gains exe / args / casemode / detected /
# probed / nospiceinit, and the existing free-form `cmd` strings are untouched
# (one of them is `{$terminal -e {ngspice -i "$N" -a || sh}}` — ngspice nested
# inside a terminal launch, which is why the executable cannot be parsed out of
# `cmd` and needs a field of its own).
#
# THE LOAD-BEARING CHECKS, and why:
#   CS150   BACKWARD COMPATIBILITY, half 1: a simrc written before these fields
#           existed must round-trip BYTE-IDENTICALLY through the new code. The
#           fixture simrc_pre_casemode was generated by the PRE-CHANGE
#           save_sim_defaults -- but be exact about what that buys, because the
#           receipt's first draft was not: the POST-change save_sim_defaults
#           emits these same bytes for a default configuration (verified with
#           `cmp` in both directions), which is the very property being
#           asserted. So CS150 asserts DETERMINISM + ADDITIVITY (the new code
#           adds not one line to a row nobody configured), and CS150b asserts
#           the fixture has not been quietly regenerated WITH profile lines in
#           it. The before/after evidence proper is the HEAD-binary comparison
#           recorded in receipts/06-simulator-profiles.md, not this check.
#   CS154b  the READ side of validation, which is the half that matters: a
#           hand-edited simrc is plain Tcl and never passes through
#           sim_profile_set, so `casemode sideways` / `detected {yes please}`
#           must read as UNSET rather than be believed.
#   CS156   A1's expressibility requirement: `casemode` (requested) and
#           `detected` (measured) must stay SEPARATE fields, or item 13 cannot
#           build a dropdown that refuses a mode the binary will silently
#           ignore. The check asserts both halves of one disagreement at once.
#   CS153e  the PERSISTENCE guard, and the one value that got past its first
#           revision: `a}b` braces to `{a}b}`, which `info complete` calls
#           complete and `set` rejects, so the emitted line made the whole simrc
#           unsourceable. CS153f is its acceptance half.
#   CS151g  the normalizer must complete a row that arrived carrying ONE field.
#           That is not a contrived shape: it is what a user who changed nothing
#           but A2's `-n` box gets back out of their own simrc.
#   CS160   THE RULING that `sim_is_xyce` does NOT consult `exe`. Item 4 made it
#           load-bearing for the Ctrl-K senders (hilight.c), so changing what it
#           answers changes fold-vs-uppercase behaviour four items after the
#           fact. It reads `cmd` and only `cmd`, and this pins that with the exe
#           deliberately pointing the other way.
#   CS165   BACKWARD COMPATIBILITY, half 2: the pre-batch ASE state fixture must
#           still round-trip byte-identically now the schema has a 17th key.
#           `ase::omit_if_empty` is what makes that possible.
#   CS166   NO Tk. `src/ase.tcl` is sourced at startup and runs true-headless;
#           the whole suite runs under --nogui, and this additionally proves no
#           new proc reaches for a Tk command (item 13 adds the widgets, and
#           must not put them here).
#
# Run TRUE HEADLESS from the repo root (needs no display):
#   ./src/xschem --nogui --pipe -q --nolog --script tests/headless/test_sim_profiles.tcl

source [file join [file dirname [info script]] scratch.tcl]

set fail 0
set npass 0
proc check {name ok detail} {
  global fail npass
  if {$ok} { puts "ok:   $name $detail"; incr npass } \
  else { puts "FAIL: $name $detail"; incr fail }
}
proc eqcheck {name got want} {
  check $name [expr {$got eq $want}] "(got '$got' want '$want')"
}
# every call goes through this: a proc that does not exist yet must FAIL a
# check, never abort the file with no RESULT line
proc pcall {args} {
  if {[catch {uplevel 1 $args} r]} { return "ERR:$r" }
  return $r
}
# 1 when the command raised a Tcl error (the refusals)
proc raises {args} {
  return [expr {[catch {uplevel 1 $args}] ? 1 : 0}]
}
# dict read that cannot abort the file: a missing key (or a value that is not a
# dict at all, which is what pcall returns when the proc under test is absent)
# yields a marker instead of a Tcl error. Same reason as CS157c's guard.
proc dg {d k} {
  if {[catch {dict get $d $k} v]} { return "NO:$k" }
  return $v
}
# A `sim` array element read that cannot ABORT the file. Same reason as `dg` and
# as CS163k's abort-proofing: a missing element is a Tcl error at substitution
# time, outside any `pcall`, and it would end the file with NO RESULT line -- under
# which every sabotage reads as "nothing went red" (LEDGER carry-forward from items
# 1, 2 and 5b). MEASURED: with both source files reverted to HEAD, CS151h's direct
# `$::sim(spice,1,exe)` aborted the run after ONE check.
proc el {name} {
  if {[info exists ::sim($name)]} { return $::sim($name) }
  return "NOELEMENT"
}
proc slurp {p} {
  if {[catch {open $p rb} f]} { return "ERR:$f" }
  set d [read $f]; close $f; return $d
}

set here    [file normalize [file dirname [info script]]]
set repo    [file normalize [file join $here .. ..]]
set fixdir  [file join $here fixtures]
set tmp     [test_scratch simprof]

# an isolated USER_CONF_DIR: nothing here may touch the developer's ~/.xschem
set ::USER_CONF_DIR [file join $tmp conf]
file mkdir $::USER_CONF_DIR

# reload the sim() array from a simrc placed in the isolated conf dir
proc load_simrc {srcfile} {
  global USER_CONF_DIR
  file copy -force $srcfile [file join $USER_CONF_DIR simrc]
  if {[info exists ::sim]} { unset ::sim }
  set_sim_defaults
}
# built-in defaults, no simrc at all
proc load_builtin_defaults {} {
  global USER_CONF_DIR
  file delete -force [file join $USER_CONF_DIR simrc]
  if {[info exists ::sim]} { unset ::sim }
  set_sim_defaults
}

# ===========================================================================
# A — the pre-batch simrc still round-trips BYTE-IDENTICALLY  (compat, half 1)
# ===========================================================================
set pre [file join $fixdir simrc_pre_casemode]
if {![file isfile $pre]} {
  puts "FAIL: CS150-pre-batch-simrc-fixture-missing ($pre) : FAIL"
  incr fail
} else {
  # the fixture must not itself carry any of the new fields, or CS150 is vacuous
  set pretxt [slurp $pre]
  set seen {}
  foreach f {exe args casemode detected probed nospiceinit} {
    if {[string first ",$f)" $pretxt] >= 0} { lappend seen $f }
  }
  eqcheck CS150b-fixture-is-really-pre-item6 $seen {}

  load_simrc $pre
  set out [file join $tmp resaved_simrc]
  pcall save_sim_defaults $out
  # ONE assertion, two facts: the bytes are unchanged AND the new fields really
  # are present in memory (so this is not passing because nothing happened)
  eqcheck CS150-pre-batch-simrc-round-trips-byte-identical \
    "identical=[expr {[slurp $out] eq $pretxt}]\
 normalized=[pcall info exists ::sim(spice,0,exe)]" \
    "identical=1 normalized=1"
}

# ===========================================================================
# B — the row shape, and reads that cannot fail
# ===========================================================================
eqcheck CS151-field-defaults-are-the-canonical-six \
  [pcall sim_profile_field_defaults] {exe {} args {} casemode {} detected {} probed {} nospiceinit 0}
eqcheck CS151b-field-name-order [pcall sim_profile_fields] \
  {exe args casemode detected probed nospiceinit}

load_builtin_defaults
set missing {}
foreach tool [pcall set ::sim(tool_list)] {
  for {set i 0} {$i < $::sim($tool,n)} {incr i} {
    foreach f [pcall sim_profile_fields] {
      if {![info exists ::sim($tool,$i,$f)]} { lappend missing $tool,$i,$f }
    }
  }
}
eqcheck CS151c-normalize-covers-every-row-of-every-tool $missing {}
# and no built-in row proposes an executable: an empty `exe` is what keeps
# today's behaviour (cmd for the Simulation menu, a bare ngspice for ASE-L)
eqcheck CS151d-no-builtin-row-gets-an-exe \
  "[pcall sim_profile_get spice 0 exe][pcall sim_profile_get spice 2 exe]" {}
# THE RC ROUTE, driven the way an rc actually drives it, with NO hand call to the
# normalizer. RESTATED 2026-08-17: this check used to call sim_profile_normalize
# directly, which no production path does once the array exists -- and that is
# precisely the hole it was supposed to cover. `cadence_style_rc` /
# `~/.xschem/xschemrc` call set_sim_defaults and THEN append a row; the array
# already exists by then, so a normalizer gated on "did this call rebuild the
# array" never walked again and the row kept `args casemode detected probed
# nospiceinit` MISSING for the whole session (measured on this tree). The gate is
# a row-count memo now. `sim_is_xyce` is a second real reader -- token.c reaches
# it from a graph redraw -- and it must not undo the shape.
set ::netlist_type spice
set rcrow [pcall set ::sim(spice,n)]
set ::sim(spice,$rcrow,cmd) {ngspice -b "$N"}
set ::sim(spice,$rcrow,name) {rc row}
set ::sim(spice,$rcrow,exe) /usr/bin/ngspice
incr ::sim(spice,n)
pcall set_sim_defaults
set rcmiss {}
foreach f [pcall sim_profile_fields] {
  if {![info exists ::sim(spice,$rcrow,$f)]} { lappend rcmiss $f }
}
eqcheck CS151f-a-row-an-rc-appended-is-completed-through-set_sim_defaults \
  "missing=<$rcmiss> exe=[pcall sim_profile_get spice $rcrow exe]" \
  "missing=<> exe=/usr/bin/ngspice"
pcall sim_is_xyce
set rcmiss2 {}
foreach f [pcall sim_profile_fields] {
  if {![info exists ::sim(spice,$rcrow,$f)]} { lappend rcmiss2 $f }
}
# The memo's TWO answers, which is what makes it a guard rather than a coin flip:
# 0 when nothing moved (that is the redraw path -- sim_is_xyce re-enters
# set_sim_defaults per cross-probe, and item 3's rule is "never poll a walk from
# a redraw"), 1 the moment a row appears, which is the only way an unshaped row
# can exist.
set memo_same [pcall sim_profile_normalize_if_changed]
set ::sim(spice,[pcall set ::sim(spice,n)],cmd) {ngspice "$N"}
incr ::sim(spice,n)
set memo_moved [pcall sim_profile_normalize_if_changed]
eqcheck CS151i-a-later-reader-keeps-the-shape-and-the-memo-notices-a-new-row \
  "missing=<$rcmiss2> same=$memo_same moved=$memo_moved" "missing=<> same=0 moved=1"
load_builtin_defaults

# THE VALUES both shape builders plant, not just the keys. `nospiceinit 0` is the
# one that matters: item 13 puts a Tk -textvariable on these elements, and an
# empty string where a 0 belongs is a `-n` box that reads as off and saves as
# garbage -- which is what the normalizer's own comment says it exists to
# prevent. Asserting only `info exists` let BOTH builders be mutated to plant {}
# with the whole suite green (measured).
set shapevals {}
foreach {f d} [pcall sim_profile_field_defaults] {
  lappend shapevals $f=<[el spice,1,$f]>
}
set addn2 [pcall set ::sim(spice,n)]
pcall simconf_add spice
set addvals {}
foreach {f d} [pcall sim_profile_field_defaults] {
  lappend addvals $f=<[el spice,$addn2,$f]>
}
eqcheck CS151h-both-shape-builders-plant-the-field-DEFAULTS \
  "normalize:$shapevals add:$addvals" \
  "normalize:exe=<> args=<> casemode=<> detected=<> probed=<> nospiceinit=<0>\
 add:exe=<> args=<> casemode=<> detected=<> probed=<> nospiceinit=<0>"
load_builtin_defaults

# nothing configured at all (a very early rc, or an `unset sim`): the walk must
# return quietly rather than error or invent an array, because there is no
# sim(tool_list) to walk. The guard that does this had no check either.
catch {unset ::sim}
eqcheck CS151j-normalize-with-no-configuration-is-a-quiet-no-op \
  "err=[catch {sim_profile_normalize}] created=[info exists ::sim]\
 stamp=<[pcall sim_profile_shape_stamp]>" "err=0 created=0 stamp=<>"
load_builtin_defaults

# THE HOLE A PER-ROW SHORT CIRCUIT HAD, and the reason sim_profile_normalize no
# longer has one. The persister writes only the fields that DIFFER from their
# default, so a user who changed nothing but A2's `-n` box gets a simrc row
# carrying `nospiceinit` ALONE -- and a normalizer that decides "this row is
# already shaped" by probing one field skips it and leaves the other five
# missing for the whole session. Driven end to end through a real save + reload,
# because that is the only route that produces such a row. `profilefields=1` is
# the premise: if the persister ever wrote more, the check would be vacuous.
load_builtin_defaults
pcall sim_profile_set spice 2 nospiceinit 1
set nsionly [file join $tmp simrc_nsi_only]
pcall save_sim_defaults $nsionly
set nsitxt [slurp $nsionly]
load_simrc $nsionly
set gone {}
foreach f [pcall sim_profile_fields] {
  if {![info exists ::sim(spice,2,$f)]} { lappend gone $f }
}
eqcheck CS151g-a-row-carrying-only-its-last-field-is-still-completed \
  "profilefields=[regexp -all \
     {set sim\(spice,2,(exe|args|casemode|detected|probed|nospiceinit)\)} $nsitxt]\
 missing=<$gone> nsi=[pcall sim_profile_get spice 2 nospiceinit]" \
  "profilefields=1 missing=<> nsi=1"
load_builtin_defaults

# a row added the way item 13's Add button will add one gets the full shape at
# once, so a sim_profile_set on it succeeds immediately (the setter refuses a row
# that is not configured, and `incr sim($tool,n)` is what configures it)
set addn [pcall set ::sim(spice,n)]
pcall simconf_add spice
eqcheck CS151e-a-newly-added-row-has-the-full-shape \
  "n=[pcall set ::sim(spice,n)] exe=[pcall info exists ::sim(spice,$addn,exe)]\
 set=[pcall sim_profile_set spice $addn casemode preserve]" \
  "n=[expr {$addn + 1}] exe=1 set=preserve"
load_builtin_defaults

eqcheck CS152-get-on-an-unconfigured-row-returns-the-default \
  [pcall sim_profile_get spice 99 casemode] {}
eqcheck CS152b-get-of-an-unknown-field-returns-empty \
  [pcall sim_profile_get spice 0 no_such_field] {}
# Every refusal below is paired with an ACCEPTANCE in the same assertion. A
# refusal alone is vacuous evidence: before this item existed the proc did not
# exist either, so `raises` answered 1 for every one of them.
eqcheck CS152c-set-of-an-unknown-field-raises \
  "refused=[string match {*unknown profile field*} \
     [pcall sim_profile_set spice 0 no_such_field x]]\
 accepted=[pcall sim_profile_set spice 0 casemode fold]" "refused=1 accepted=fold"
eqcheck CS152d-set-of-an-unconfigured-row-raises \
  "refused=[raises sim_profile_set spice 99 casemode fold]\
 accepted=[pcall sim_profile_set spice 0 casemode preserve]" "refused=1 accepted=preserve"
pcall sim_profile_set spice 0 casemode {}

# ===========================================================================
# C — validation, on write AND on read
# ===========================================================================
set ver50 {/home/qflow/dev/ngspice_test/build-ver_50/src/ngspice}
pcall sim_profile_set spice 2 exe $ver50
eqcheck CS153-exe-round-trips [pcall sim_profile_get spice 2 exe] $ver50
# a `$` in an exe survives verbatim: `cmd` strings carry $terminal / $env(HOME)
# and are subst'ed at USE time, and these fields follow that convention
pcall sim_profile_set spice 2 exe {$env(HOME)/dev/ngspice}
eqcheck CS153b-a-dollar-in-exe-is-stored-verbatim \
  [pcall sim_profile_get spice 2 exe] {$env(HOME)/dev/ngspice}
pcall sim_profile_set spice 2 args {-D casemode=preserve}
eqcheck CS153c-args-is-a-list \
  [llength [pcall sim_profile_get spice 2 args]] 2
# a value that would not survive being braced into simrc is refused: the writer
# emits `set sim(...) {$value}`, so an unbalanced brace would produce a file
# that cannot be sourced at all
eqcheck CS153d-unbraceable-value-refused \
  "refused=[raises sim_profile_set spice 2 exe "a\{b"]\
 kept=[pcall sim_profile_get spice 2 exe]" "refused=1 kept=\$env(HOME)/dev/ngspice"
# An unbalanced CLOSE brace is the case the first guard here PASSED. `info
# complete "{a}b}"` answers 1, so `a}b` was stored, written as
# `set sim(spice,2,exe) {a}b}` and the whole of ~/.xschem/simrc then failed to
# load with `extra characters after close-brace` -- measured, and the exact
# failure the guard exists to prevent. Written as \175 so THIS file stays
# sourceable (the literal defeated a first draft of this very check).
set badclose "a\175b"
eqcheck CS153e-an-unbalanced-close-brace-is-refused-too \
  "refused=[raises sim_profile_set spice 2 exe $badclose]\
 kept=[pcall sim_profile_get spice 2 exe]" "refused=1 kept=\$env(HOME)/dev/ngspice"
# The ACCEPTANCE half, so the guard cannot pass CS153d/CS153e by refusing
# everything: balanced inner braces, a space and a `$` all survive being written
# and sourced back for real.
set okbraces {/opt/x{y z}/ngspice $V}
pcall sim_profile_set spice 2 exe $okbraces
set bracefile [file join $tmp simrc_braces]
pcall save_sim_defaults $bracefile
load_simrc $bracefile
eqcheck CS153f-balanced-braces-survive-a-real-save-and-reload \
  [pcall sim_profile_get spice 2 exe] $okbraces
pcall sim_profile_set spice 2 exe {$env(HOME)/dev/ngspice}
# THE OTHER PARSER, and the second revision of the same class of bug. The guard
# tests the emitted line with the LIST parser (llength/lindex); the simrc is read
# by `source`, i.e. the SCRIPT parser, and inside braces those two disagree on
# exactly one thing: backslash-newline, which the script parser collapses to a
# single space and the list parser keeps. MEASURED end to end through
# save_sim_defaults + source: `x BACKSLASH NEWLINE y` (78-5c-0a-79) went in and
# `x SPACE y` (78-20-79) came back, and a second save then DIFFERED from the
# first -- so the byte-stability CS153f/CS158d advertise broke on a value the
# guard had accepted. A bare CR is the same defect by another route: channel
# translation turns it into a newline on the way in (78-0d-79 -> 78-0a-79).
# Both refused, and the ACCEPTANCE half is in the same assertion because the
# lookalikes DO survive and must not become collateral damage: a lone backslash
# round-trips byte-identically through a real save + reload, and a bare newline
# still validates.
set BS [format %c 92]
set CR [format %c 13]
set NL [format %c 10]
pcall sim_profile_set spice 2 args x${BS}y
set bsfile [file join $tmp simrc_bs]
pcall save_sim_defaults $bsfile
load_simrc $bsfile
set bsback [pcall sim_profile_get spice 2 args]
set bsfile2 [file join $tmp simrc_bs2]
pcall save_sim_defaults $bsfile2
eqcheck CS153g-the-script-parsers-two-divergences-are-refused \
  "bsnl=[raises sim_profile_set spice 2 args x${BS}${NL}y]\
 cr=[raises sim_profile_set spice 2 args x${CR}y]\
 nl=[pcall sim_profile_valid args x${NL}y]\
 bs_back=[expr {$bsback eq "x${BS}y"}]\
 bs_stable=[expr {[slurp $bsfile2] eq [slurp $bsfile]}]" \
  "bsnl=1 cr=1 nl=1 bs_back=1 bs_stable=1"
pcall sim_profile_set spice 2 args {}
pcall sim_profile_set spice 2 exe {$env(HOME)/dev/ngspice}
eqcheck CS154-bad-casemode-token-refused \
  "refused=[raises sim_profile_set spice 2 casemode sideways]\
 accepted=[pcall sim_profile_set spice 2 casemode distinguish]" \
  "refused=1 accepted=distinguish"
eqcheck CS154c-unknown-is-not-a-requestable-mode \
  "refused=[raises sim_profile_set spice 2 casemode unknown]\
 kept=[pcall sim_profile_get spice 2 casemode]" "refused=1 kept=distinguish"
pcall sim_profile_set spice 2 casemode {}
# THE READ SIDE: a hand-edited simrc bypasses the setter entirely
set ::sim(spice,2,casemode) sideways
set ::sim(spice,2,detected) {yes please}
eqcheck CS154b-garbage-from-a-hand-edited-simrc-reads-as-unset \
  "[pcall sim_profile_get spice 2 casemode]/[pcall sim_profile_get spice 2 detected]" {/}
set ::sim(spice,2,casemode) {}
set ::sim(spice,2,detected) {}
eqcheck CS154d-bad-probed-value-refused \
  "refused=[raises sim_profile_set spice 2 probed {a b c}]\
 accepted=[pcall sim_profile_set spice 2 probed {time 1 mtime 2}]" \
  "refused=1 accepted=time 1 mtime 2"
pcall sim_profile_set spice 2 probed {}
eqcheck CS154e-nospiceinit-refuses-garbage \
  "refused=[raises sim_profile_set spice 2 nospiceinit maybe]\
 kept=[pcall sim_profile_get spice 2 nospiceinit]" "refused=1 kept=0"
eqcheck CS154f-nospiceinit-accepts-a-boolean \
  [pcall sim_profile_set spice 2 nospiceinit 1] 1
# The per-field LIST arms, which until now nothing could move (both were mutated
# to `return 1` with the suite green -- reported by the verifier, closed here). An
# unmatched double quote is the value that reaches them: it passes the line guard
# above (braced, it is one word coming back byte-equal) and yet is not a
# well-formed LIST, so `args` and `detected` must refuse it -- item 8 will compose
# `args` with `{*}`, which explodes there rather than here -- while `exe` is a
# plain string and must still take it.
# The `read=` legs are the half that matters and the reason those arms are not
# merely belt: a hand-edited simrc plants the value directly, `sim_profile_get`
# validates on READ, and a `foreach`/`llength` on a non-list there RAISES -- which
# would abort whichever caller happened to read that row, instead of the value
# reading as unset. So each list arm is driven both ways.
set qval "[format %c 34]foo"
set g_args [raises sim_profile_set spice 2 args $qval]
set g_det  [raises sim_profile_set spice 2 detected $qval]
set g_exe  [pcall sim_profile_set spice 2 exe $qval]
set ::sim(spice,2,detected) $qval
set ::sim(spice,2,probed) $qval
set g_rdet [pcall sim_profile_get spice 2 detected]
set g_rpro [pcall sim_profile_get spice 2 probed]
set ::sim(spice,2,detected) {}
set ::sim(spice,2,probed) {}
eqcheck CS154g-a-non-list-is-refused-for-the-list-fields-and-kept-for-exe \
  "args=$g_args detected=$g_det exe=$g_exe read=<$g_rdet><$g_rpro>" \
  "args=1 detected=1 exe=$qval read=<><>"
pcall sim_profile_set spice 2 exe {$env(HOME)/dev/ngspice}

# ===========================================================================
# D — the requested mode: per profile, with a global floor  (B1)
# ===========================================================================
set ::sim_case_mode fold
eqcheck CS155-silent-profile-falls-to-the-floor [pcall sim_profile_casemode spice 2] fold
set ::sim_case_mode distinguish
eqcheck CS155b-the-floor-is-the-floor [pcall sim_profile_casemode spice 2] distinguish
pcall sim_profile_set spice 2 casemode preserve
eqcheck CS155c-the-profile-beats-the-floor [pcall sim_profile_casemode spice 2] preserve
set ::sim_case_mode sideways
pcall sim_profile_set spice 2 casemode {}
eqcheck CS155d-a-garbage-floor-falls-to-fold [pcall sim_profile_casemode spice 2] fold
set ::sim_case_mode fold

# ===========================================================================
# E — A1: requested and measured are DIFFERENT fields
# ===========================================================================
pcall sim_profile_set spice 2 casemode preserve
pcall sim_profile_set spice 2 detected {fold}
# one assertion, one disagreement: the request stands, and the capability says no
eqcheck CS156-requested-and-measured-are-separate \
  "req=[pcall sim_profile_casemode spice 2]\
 supports=[pcall sim_profile_supports spice 2 preserve]" "req=preserve supports=0"
pcall sim_profile_set spice 2 detected {}
eqcheck CS156b-never-probed-supports-nothing-not-even-fold \
  "[pcall sim_profile_supports spice 2 fold][pcall sim_profile_supports spice 2 preserve]" 00
eqcheck CS156c-selectable-is-fold-alone-until-probed \
  [pcall sim_profile_selectable spice 2] fold
pcall sim_profile_set spice 2 detected {distinguish fold}
eqcheck CS156d-selectable-is-what-was-measured-in-canonical-order \
  [pcall sim_profile_selectable spice 2] {fold distinguish}
# Both halves in one assertion. `supports … unknown` = 0 ALONE is a tautology of
# the data model -- `detected` is filtered through the canonical three, so
# `unknown` can never be in it and no single mutation can make this answer 1 (I
# tried: dropping the mode guard and dropping the filter both leave it 0). Paired
# with a mode that WAS measured it carries evidence again.
eqcheck CS156e-supports-refuses-a-non-mode-and-accepts-a-measured-one \
  "unknown=[pcall sim_profile_supports spice 2 unknown]\
 fold=[pcall sim_profile_supports spice 2 fold]" "unknown=0 fold=1"
set ::sim(spice,2,detected) {preserve nonsense}
eqcheck CS156f-a-hand-planted-garbage-capability-is-dropped \
  [pcall sim_profile_detected spice 2] {}
pcall sim_profile_set spice 2 detected {}

# ===========================================================================
# F — probe provenance: recorded here, never RUN here (the probe is item 7)
# ===========================================================================
set fakeexe [file join $tmp fake_ngspice]
set f [open $fakeexe w]; puts $f "#!/bin/sh\nexit 0"; close $f
file attributes $fakeexe -permissions 0755
pcall sim_profile_set spice 2 exe $fakeexe
eqcheck CS157-never-probed-is-stale [pcall sim_profile_probe_stale spice 2] 1
set t0 [clock seconds]
eqcheck CS157b-probe-record-filters-and-orders \
  [pcall sim_profile_probe_record spice 2 {distinguish bogus fold}] {fold distinguish}
set p [pcall sim_profile_get spice 2 probed]
# abort-proofed on purpose: an EMPTY `probed` (which is what a broken or absent
# probe_record leaves) makes a bare `dict get` raise, and a Tcl error here would
# end the file with no RESULT line at all -- under which a sabotage reads as
# "nothing went red" (LEDGER carry-forward from items 1 and 2).
# RESTATED 2026-08-17: `time > 0` was not an assertion about a timestamp --
# hard-coding the stamp to `time 1` left the suite green (measured). The stamp is
# PROVENANCE: it has to be the moment of the measurement, so it is compared with
# the clock, with a 2 s window for a loaded machine.
eqcheck CS157c-probe-record-stamps-the-measurement-time-and-mtime \
  "time=[pcall expr {[dict exists $p time] && abs([dict get $p time] - $t0) <= 2}]\
 mtime=[pcall expr {[dict get $p mtime] eq [file mtime $fakeexe]}]" {time=1 mtime=1}
eqcheck CS157d-a-fresh-measurement-is-not-stale [pcall sim_profile_probe_stale spice 2] 0
# the case-capable ngspice build moved THREE times in four days during this
# batch, so a moved binary is the normal case
file mtime $fakeexe [expr {[file mtime $fakeexe] + 120}]
eqcheck CS157e-a-moved-binary-makes-the-measurement-stale \
  [pcall sim_profile_probe_stale spice 2] 1
pcall sim_profile_set spice 2 exe {/no/such/binary/anywhere}
eqcheck CS157f-an-exe-that-cannot-be-found-is-stale \
  [pcall sim_profile_probe_stale spice 2] 1
eqcheck CS157g-exe-path-of-an-absent-exe-is-empty \
  [pcall sim_profile_exe_path spice 2] {}
pcall sim_profile_set spice 2 exe $fakeexe
eqcheck CS157h-exe-path-resolves-an-absolute-exe \
  [pcall sim_profile_exe_path spice 2] $fakeexe
# an exe written the way every `cmd` string already writes a path: variables are
# expanded HERE (variables only -- a `[exec ...]` must not run from a staleness
# query), or a perfectly good profile answers {} and reads as stale forever
set ::SIMPROF_TEST_DIR [file dirname $fakeexe]
pcall sim_profile_set spice 2 exe {$::SIMPROF_TEST_DIR/fake_ngspice}
eqcheck CS157i-exe-path-expands-a-variable \
  "path=[pcall sim_profile_exe_path spice 2] stale=[pcall sim_profile_probe_stale spice 2]" \
  "path=$fakeexe stale=1"
# A reference that is NOT at offset 0 -- which the REPLACEMENT expander got wrong
# in its first draft and nothing here could catch, because every exe in this file
# began with its variable. `regexp -start` does NOT move the `^` anchor (measured
# in tclsh 8.6.14: with `-start 5` an anchored pattern simply fails), so
# `/opt/$env(HOME)/ngspice` came back UNEXPANDED -- and an unexpanded path is
# exactly the "answers {} for a perfectly good profile, then reports stale
# forever" failure the expansion exists to prevent.
set ::SIMPROF_EXE_NAME [file tail $fakeexe]
pcall sim_profile_set spice 2 exe "[file dirname $fakeexe]/\$::SIMPROF_EXE_NAME"
# Both reference forms, because they are two separate patterns in the expander and
# the anchor bug was in one of them at a time.
eqcheck CS157n-a-variable-that-is-not-at-the-start-expands-too \
  "path=[pcall sim_profile_exe_path spice 2]\
 mid=[pcall sim_profile_expand_vars {/a/$::SIMPROF_EXE_NAME/b}]\
 braced=[pcall sim_profile_expand_vars "/a/\$\{::SIMPROF_EXE_NAME\}/b"]" \
  "path=$fakeexe mid=/a/[file tail $fakeexe]/b braced=/a/[file tail $fakeexe]/b"
pcall sim_profile_set spice 2 exe {$::SIMPROF_NO_SUCH_VAR/ngspice}
eqcheck CS157j-an-unset-variable-is-cannot-locate-not-an-error \
  [pcall sim_profile_exe_path spice 2] {}
# the side effect is the evidence: with commands substituted the expansion
# answers {} as well (a relative path that resolves to nothing), so only an
# observable side effect can tell the two apart. `set` rather than `exec` so the
# check does not depend on any binary being installed.
catch {unset ::SIMPROF_COMMAND_RAN}
pcall sim_profile_set spice 2 exe {[set ::SIMPROF_COMMAND_RAN 1]/ngspice}
eqcheck CS157k-a-command-substitution-does-not-run \
  "path=[pcall sim_profile_exe_path spice 2]\
 ran=[info exists ::SIMPROF_COMMAND_RAN]" "path= ran=0"
# THE CASE `-nocommands` DOES NOT COVER, and the reason this expansion no longer
# uses `subst` at all: Tcl evaluates a `[...]` that sits inside the ARRAY INDEX
# of a variable reference even with command substitution suppressed. MEASURED on
# 8.6.14 -- `set ::RAN 0; subst -nocommands -nobackslashes {$A([set ::RAN 1])/x}`
# leaves ::RAN at 1 -- and end to end on this tree an `exe` of
# `$env([exec touch <path>])/ngspice` created that file during a pure STALENESS
# query, while exe_path returned {} and looked innocent. CS157k passed throughout,
# because a TOP-LEVEL `[...]` is the one shape `-nocommands` does suppress.
# `refused=1` reads the expander's own refusal rather than only the side effect,
# because the two mechanisms are not the same evidence: `set` does not substitute
# inside a variable NAME, so even without the explicit refusal nothing would run
# here -- and a line that cannot be moved is not covered. This asserts the
# expander refuses the FORM, which is what keeps the guarantee if the lookup ever
# stops going through `set`.
catch {unset ::SIMPROF_INDEX_RAN}
pcall sim_profile_set spice 2 exe {$env([set ::SIMPROF_INDEX_RAN 1])/ngspice}
eqcheck CS157l-a-command-substitution-inside-an-array-index-does-not-run \
  "path=[pcall sim_profile_exe_path spice 2]\
 refused=[string match {*refusing a substitution*} \
   [pcall sim_profile_expand_vars {$env([set ::SIMPROF_INDEX_RAN 1])/ngspice}]]\
 ran=[info exists ::SIMPROF_INDEX_RAN]" "path= refused=1 ran=0"
# A1's rule lives in probe_record's FILTER: a probe that measured `preserve` and
# nothing else must not leave a row claiming `fold`. The only probe_record drive
# in this file passed a list that already contained fold, so a filter mutated to
# add fold unconditionally stayed green (measured) -- and item 13's dropdown reads
# exactly this.
pcall sim_profile_set spice 3 exe $fakeexe
eqcheck CS157m-probe-record-cannot-add-a-mode-it-was-not-given \
  "rec=[pcall sim_profile_probe_record spice 3 {preserve}]\
 detected=[pcall sim_profile_detected spice 3]\
 fold=[pcall sim_profile_supports spice 3 fold]\
 preserve=[pcall sim_profile_supports spice 3 preserve]\
 selectable=[pcall sim_profile_selectable spice 3]" \
  "rec=preserve detected=preserve fold=0 preserve=1 selectable=preserve"
# `modes` EMPTY is a legal probe_record call and means "measured, delivers nothing
# we recognise". The row must not then be offered a mode: keying the never-probed
# fallback off `detected` instead of `probed` had sim_profile_selectable offering
# `fold` for a binary sim_profile_supports refused in the same breath -- two procs
# of one item disagreeing about one binary, and A1 broken for the one binary that
# had actually been measured. `stale=0` is the premise: this row WAS measured, so
# this is not the unprobed case CS156c covers.
pcall sim_profile_probe_record spice 3 {}
eqcheck CS156g-measured-and-delivering-nothing-offers-nothing \
  "probed=[expr {[pcall sim_profile_get spice 3 probed] ne {}}]\
 stale=[pcall sim_profile_probe_stale spice 3]\
 fold=[pcall sim_profile_supports spice 3 fold]\
 selectable=<[pcall sim_profile_selectable spice 3]>" \
  "probed=1 stale=0 fold=0 selectable=<>"
pcall sim_profile_set spice 2 exe $fakeexe

# ===========================================================================
# G — persistence: only what differs from the default, and it comes back
# ===========================================================================
load_builtin_defaults
pcall sim_profile_set spice 2 exe {$env(HOME)/dev/ngspice}
pcall sim_profile_set spice 2 args {-D casemode=preserve}
pcall sim_profile_set spice 2 casemode preserve
pcall sim_profile_set spice 2 detected {fold preserve}
pcall sim_profile_set spice 2 nospiceinit 1
set written [file join $tmp written_simrc]
pcall save_sim_defaults $written
set wtxt [slurp $written]
eqcheck CS158-only-the-set-fields-are-written \
  "exe=[regexp -all {set sim\(spice,2,exe\)} $wtxt]\
 nsi=[regexp -all {set sim\(spice,2,nospiceinit\)} $wtxt]\
 probed=[regexp -all {set sim\(spice,\d+,probed\)} $wtxt]\
 otherrows=[regexp -all {set sim\(spice,[013],(exe|casemode)\)} $wtxt]" \
  "exe=1 nsi=1 probed=0 otherrows=0"
eqcheck CS158b-the-dollar-is-written-braced-not-substituted \
  [regexp -all {set sim\(spice,2,exe\) \{\$env\(HOME\)/dev/ngspice\}} $wtxt] 1
# and the file sources back to the same values, `$` intact
load_simrc $written
set back [join [list [pcall sim_profile_get spice 2 exe] \
                     [pcall sim_profile_get spice 2 args] \
                     [pcall sim_profile_casemode spice 2] \
                     [pcall sim_profile_get spice 2 nospiceinit] \
                     [pcall sim_profile_selectable spice 2]] |]
eqcheck CS158c-a-written-profile-comes-back-verbatim $back \
  "\$env(HOME)/dev/ngspice|-D casemode=preserve|preserve|1|fold preserve"
# a second save of the loaded file is byte-stable too
set again [file join $tmp written_simrc2]
pcall save_sim_defaults $again
eqcheck CS158d-a-simrc-with-profile-fields-is-byte-stable \
  "stable=[expr {[slurp $again] eq $wtxt}]\
 hasfields=[regexp -all {set sim\(spice,2,(exe|args|casemode|detected|nospiceinit)\)} $wtxt]" \
  "stable=1 hasfields=5"

# `probed` is the ONE field whose entire purpose is surviving between sessions,
# and nothing asserted that it did: the persister could drop it with every other
# check green (measured), and each reloaded profile would then be permanently
# stale -- item 7 re-probing every session while `detected` went on claiming
# capabilities. The staleness answer after a real save + reload is the
# consequence, so this is not a check about a line of text.
load_builtin_defaults
set probedexe [file join $tmp fake_ngspice2]
set pfd [open $probedexe w]; puts $pfd "#!/bin/sh\nexit 0"; close $pfd
file attributes $probedexe -permissions 0755
pcall sim_profile_set spice 2 exe $probedexe
pcall sim_profile_probe_record spice 2 {fold preserve}
set pw [file join $tmp simrc_probed]
pcall save_sim_defaults $pw
set pwtxt [slurp $pw]
load_simrc $pw
eqcheck CS158e-the-probe-stamp-survives-a-save-and-reload \
  "line=[regexp -all {set sim\(spice,2,probed\) \{time \d+ mtime \d+\}} $pwtxt]\
 back=[expr {[pcall sim_profile_get spice 2 probed] ne {}}]\
 stale=[pcall sim_profile_probe_stale spice 2]\
 detected=[pcall sim_profile_detected spice 2]" \
  "line=1 back=1 stale=0 detected=fold preserve"

# Persistence for a tool that is NOT `spice`. Every other persistence check here
# names a spice row, so the persister could refuse the profile fields for the
# other six tools in sim(tool_list) with the suite green (measured). `spicewave`
# is a real row of a real tool, and item 13's dialog has a tab per tool.
load_builtin_defaults
pcall sim_profile_set spicewave 0 exe {/usr/local/bin/gaw}
pcall sim_profile_set spicewave 0 casemode preserve
set swf [file join $tmp simrc_spicewave]
pcall save_sim_defaults $swf
set swtxt [slurp $swf]
load_simrc $swf
eqcheck CS158f-profile-fields-persist-for-a-tool-that-is-not-spice \
  "lines=[regexp -all {set sim\(spicewave,0,(exe|casemode)\)} $swtxt]\
 exe=[pcall sim_profile_get spicewave 0 exe]\
 casemode=[pcall sim_profile_casemode spicewave 0]" \
  "lines=2 exe=/usr/local/bin/gaw casemode=preserve"

# A DECLARED CONSEQUENCE, pinned here so it cannot change silently (ruled in
# doc/claude/specs/simulator_profiles.md section 5, "an invalid hand-edited value
# is DROPPED, not preserved"): the persister writes THROUGH the validating
# reader, so a value a user hand-edited into their own simrc that does not
# validate is not written back -- their line disappears and the model reverts to
# the floor. The alternative, writing the raw element, can emit a line that makes
# the whole simrc unsourceable, which is strictly worse; item 13's dialog is where
# a typo should be reported to its author. The VALID field on the same row
# surviving is what makes this a drop and not a wipe.
load_builtin_defaults
pcall sim_profile_set spice 2 exe {/usr/local/bin/ngspice}
set ::sim(spice,2,casemode) {Preserve}
set dropf [file join $tmp simrc_dropped]
pcall save_sim_defaults $dropf
set droptxt [slurp $dropf]
eqcheck CS158g-an-invalid-hand-edited-value-is-dropped-at-the-next-save \
  "casemode=[regexp -all {set sim\(spice,2,casemode\)} $droptxt]\
 exe=[regexp -all {set sim\(spice,2,exe\)} $droptxt]\
 requested=[pcall sim_profile_casemode spice 2]" \
  "casemode=0 exe=1 requested=fold"

# ===========================================================================
# H — the row dict, the default row, and the sim_is_xyce RULING
# ===========================================================================
load_builtin_defaults
pcall sim_profile_set spice 2 casemode {}
set row [pcall sim_profile_row spice 2]
# RESTATED 2026-08-17: `fg` and `st` were in the dict and asserted by nothing --
# dropping both from the row builder left the suite green (measured). They are
# what item 8 needs in order to decide foreground vs background and whether to
# report an exit status, so the row dict is the wrong place to lose them. The
# expected fg/st are the LITERAL built-in values of spice row 2 (fg 0, st 1), not
# a re-read of the array, so a builder that copied the wrong element is caught too.
eqcheck CS159-row-carries-cmd-name-fg-st-the-raw-field-and-the-resolved-request \
  "cmd=[expr {[dg $row cmd] eq $::sim(spice,2,cmd)}] name='[dg $row name]'\
 fg=[dg $row fg] st=[dg $row st] casemode='[dg $row casemode]'\
 requested=[dg $row requested] selectable=[dg $row selectable]" \
  "cmd=1 name='Ngspice batch' fg=0 st=1 casemode='' requested=fold selectable=fold"
# a non-zero default on purpose: `0` is also what a constant-returning
# implementation answers, so asserting it would be vacuous (sabotage M50 proved
# exactly that -- forcing the internal value to -1 still read 0 through the
# bounds clamp).
set ::sim(spice,default) 3
eqcheck CS159b-default-index-is-the-tools-default [pcall sim_profile_default_index spice] 3
set ::sim(spice,default) 0
set ::sim(spice,default) 99
eqcheck CS159c-an-out-of-range-default-is-bounded [pcall sim_profile_default_index spice] 0
set ::sim(spice,default) 0
eqcheck CS159d-no-such-tool-has-no-default-row [pcall sim_profile_default_index nosuchtool] -1

# THE RULING (spec section 6): sim_is_xyce reads the configured `cmd`, and only
# `cmd`. Item 4 built hilight.c's Xyce sender fallback on its answer, so an exe
# field must not change it. Both directions, each carrying its own evidence.
set ::netlist_type spice
set ::sim(spice,default) 2
pcall sim_profile_set spice 2 exe {/opt/Xyce/bin/Xyce}
eqcheck CS160-sim_is_xyce-ignores-a-Xyce-exe \
  "exe=[pcall sim_profile_get spice 2 exe] xyce=[pcall sim_is_xyce]" \
  "exe=/opt/Xyce/bin/Xyce xyce=0"
set ::sim(spice,default) 3
pcall sim_profile_set spice 3 exe {/usr/bin/ngspice}
eqcheck CS160b-sim_is_xyce-still-answers-from-cmd \
  "exe=[pcall sim_profile_get spice 3 exe] xyce=[pcall sim_is_xyce]" \
  "exe=/usr/bin/ngspice xyce=1"
set ::sim(spice,default) 0

# ===========================================================================
# I — the ASE-L state key
# ===========================================================================
eqcheck CS161-sim_profile-is-in-the-schema \
  [expr {[lsearch -exact $ase::schema_keys sim_profile] >= 0}] 1
eqcheck CS161b-sim_profile-sits-right-after-simulator \
  [lsearch -exact $ase::schema_keys sim_profile] \
  [expr {[lsearch -exact $ase::schema_keys simulator] + 1}]
eqcheck CS161c-sim_profile-is-omitted-when-empty \
  [expr {[lsearch -exact $ase::omit_if_empty sim_profile] >= 0}] 1
set sd [pcall ase::state_default]
eqcheck CS161d-state_default-carries-an-empty-sim_profile [dg $sd sim_profile] {}
eqcheck CS161e-an-empty-sim_profile-serializes-to-nothing \
  "inschema=[expr {[lsearch -exact $ase::schema_keys sim_profile] >= 0}]\
 serialized=[expr {[string first sim_profile [pcall ase::state_serialize $sd]] >= 0}]" \
  "inschema=1 serialized=0"
# a NON-schema key would also appear -- sorted, after every schema key -- so the
# evidence that this is a first-class schema key is its LINE POSITION: third,
# right after version and simulator.
set serl [split [pcall ase::state_serialize \
   [dict replace $sd sim_profile {tool spice index 2}]] "\n"]
eqcheck CS161f-a-named-profile-IS-serialized-in-canonical-position \
  "line=[lsearch -glob $serl {sim_profile *}] text=[lindex $serl 2]" \
  "line=2 text=sim_profile {tool spice index 2}"

eqcheck CS162-backend-tool-maps-ngspice-to-spice [pcall ase::backend_tool ngspice] spice
eqcheck CS162b-an-unmapped-backend-falls-back-to-spice [pcall ase::backend_tool wombat] spice
# THE MAP ITSELF, because CS162 cannot fail for the reason it names: an unmapped
# backend also answers `spice`, so emptying the whole table left CS162 AND CS162b
# green (measured). Read the entry directly and the table is load-bearing again.
# (read through `pcall set` -- a bare `$ase::backend_tools` substitutes BEFORE
# pcall runs, so if the variable is absent the file aborts with no RESULT line
# instead of failing this check; measured against HEAD sources.)
eqcheck CS162c-the-backend-tool-map-carries-the-entry-itself \
  [pcall dict get [pcall set ase::backend_tools] ngspice] spice

load_builtin_defaults
eqcheck CS163-a-virgin-state-resolves-to-the-tool-default \
  [pcall ase::sim_profile_resolve $sd] {tool spice index 0 status default}
# `sim()` is built LAZILY -- nothing populates it at startup and its five xschem
# readers each open with a set_sim_defaults. A session that had not yet touched
# the Simulation menu resolved to `index -1`: "the tool's default row" naming no
# row at all, from a tool that has three. `existed=0` is the premise, so the
# check cannot pass on an array that was already there.
catch {unset ::sim}
eqcheck CS163k-resolve-builds-the-array-it-reads \
  "existed=[info exists ::sim] r=[pcall ase::sim_profile_resolve $sd]" \
  "existed=0 r=tool spice index 0 status default"
# ABORT-PROOFING, and it is load-bearing: if the proc under test stops building
# the array, `sim` is still unset here, and the very next checks read
# `$::sim(spice,2,name)` directly -- a Tcl error that ends the file with NO
# RESULT line, under which the sabotage reads as "nothing went red" (LEDGER
# carry-forward from items 1, 2 and 5b). Measured: mutation M05 aborted the file
# before this line existed.
load_builtin_defaults
set st2 [pcall ase::sim_profile_stamp $sd spice 2]
eqcheck CS163b-stamp-then-resolve-is-ok \
  [pcall ase::sim_profile_resolve $st2] {tool spice index 2 status ok}
eqcheck CS163c-stamp-records-the-row-name \
  [dg [dg $st2 sim_profile] name] $::sim(spice,2,name)
# rows are addressed by INDEX, so a renamed/reordered row must not be reported ok
set savedname $::sim(spice,2,name)
set ::sim(spice,2,name) {Something else entirely}
eqcheck CS163d-a-row-that-changed-name-resolves-stale \
  [dg [pcall ase::sim_profile_resolve $st2] status] stale
set ::sim(spice,2,name) $savedname
eqcheck CS163e-an-out-of-range-index-is-invalid-and-falls-back \
  [pcall ase::sim_profile_resolve [dict replace $sd sim_profile {tool spice index 42}]] \
  {tool spice index 0 status invalid}
eqcheck CS163f-an-unknown-tool-is-invalid-and-falls-back \
  [pcall ase::sim_profile_resolve [dict replace $sd sim_profile {tool wombat index 0}]] \
  {tool spice index 0 status invalid}
eqcheck CS163g-an-odd-length-sim_profile-is-invalid-not-an-error \
  [pcall ase::sim_profile_resolve [dict replace $sd sim_profile {a b c}]] \
  {tool spice index 0 status invalid}
eqcheck CS163i-a-sim_profile-naming-no-index-is-invalid \
  [pcall ase::sim_profile_resolve [dict replace $sd sim_profile {tool spice}]] \
  {tool spice index 0 status invalid}
# `2x` is the input that needs the explicit integer test: Tcl's `<` and `>=`
# fall back to STRING comparison for a non-numeric operand, and `2x` compares
# below `5` as a string, so a bounds test alone would pass it through and report
# a non-existent row as `ok` (found by sabotage M34, which the range check alone
# survived).
eqcheck CS163j-a-non-integer-index-is-invalid \
  [pcall ase::sim_profile_resolve [dict replace $sd sim_profile {tool spice index 2x}]] \
  {tool spice index 0 status invalid}
# A NON-CANONICAL INTEGER IS NOT A DIFFERENT ROW. The index becomes an ARRAY KEY,
# and `string is integer -strict` accepts `02`, `-0` and a value with surrounding
# whitespace: each passed the range test and then indexed `sim(spice,02,...)`,
# an element that does not exist, while resolve answered `ok`. MEASURED: with
# spice row 2 requesting `distinguish`, a state naming `index 02` resolved `ok`
# and the session's requested mode came back as the floor instead -- silently
# lost, and reported as fine to item 8, which is told it may run an `ok`. The
# canonical spelling is what comes back out.
pcall sim_profile_set spice 2 casemode distinguish
eqcheck CS163l-a-non-canonical-index-is-canonicalized-not-believed \
  "r=[pcall ase::sim_profile_resolve [dict replace $sd sim_profile {tool spice index 02}]]\
 mode=[pcall ase::sim_profile_casemode [dict replace $sd sim_profile {tool spice index 02}]]" \
  "r=tool spice index 2 status ok mode=distinguish"
pcall sim_profile_set spice 2 casemode {}
# A tool that is NOT spice, so that `stamp`'s and `resolve`'s tool argument is
# load-bearing: both were mutated to hard-code `spice` and the suite stayed green
# (measured). spicewave has its own rows, and item 13's dialog has a tab per tool.
pcall sim_profile_set spicewave 0 casemode preserve
set stsw [pcall ase::sim_profile_stamp $sd spicewave 0]
eqcheck CS163m-stamp-and-resolve-carry-the-tool-they-were-given \
  "r=[pcall ase::sim_profile_resolve $stsw]\
 name=[expr {[dg [dg $stsw sim_profile] name] eq $::sim(spicewave,0,name)}]\
 mode=[pcall ase::sim_profile_casemode $stsw]" \
  "r=tool spicewave index 0 status ok name=1 mode=preserve"
pcall sim_profile_set spicewave 0 casemode {}
eqcheck CS163h-clear-goes-back-to-the-default-row \
  [pcall ase::sim_profile_resolve [pcall ase::sim_profile_clear $st2]] \
  {tool spice index 0 status default}

# the session's requested mode comes from the RESOLVED row, not from the state
set ::sim_case_mode fold
pcall sim_profile_set spice 2 casemode distinguish
eqcheck CS164-state-casemode-follows-the-named-profile \
  [pcall ase::sim_profile_casemode $st2] distinguish
eqcheck CS164b-state-casemode-of-a-virgin-state-is-the-floor \
  [pcall ase::sim_profile_casemode $sd] fold
set ::sim_case_mode preserve
eqcheck CS164c-and-it-tracks-the-floor [pcall ase::sim_profile_casemode $sd] preserve
set ::sim_case_mode fold
pcall sim_profile_set spice 2 casemode {}

# ===========================================================================
# J — the pre-batch ASE state file still round-trips BYTE-IDENTICALLY
# ===========================================================================
set sfix [file join $fixdir ase_state_v1_pre_cosim.state]
if {![file isfile $sfix]} {
  puts "FAIL: CS165-pre-batch-state-fixture-missing ($sfix) : FAIL"
  incr fail
} else {
  set ftxt [slurp $sfix]
  eqcheck CS165b-state-fixture-is-really-pre-item6 \
    [expr {[string first "sim_profile" $ftxt] >= 0}] 0
  set old [pcall ase::state_load $sfix]
  set rt [file join $tmp roundtrip.state]
  pcall ase::state_save $rt $old
  eqcheck CS165-pre-batch-state-round-trips-byte-identical \
    "identical=[expr {[slurp $rt] eq $ftxt}]\
 gained_the_key=[dict exists $old sim_profile]\
 kept_unknown=[dict exists $old zz_unknown_future_key]" \
    "identical=1 gained_the_key=1 kept_unknown=1"
  # and once a profile IS named, it lands in the file and comes back
  set named [pcall ase::sim_profile_stamp $old spice 2]
  pcall ase::state_save $rt $named
  eqcheck CS165c-a-named-profile-persists-and-reloads \
    [pcall ase::sim_profile_resolve [pcall ase::state_load $rt]] \
    {tool spice index 2 status ok}
}

# ===========================================================================
# K — NO Tk in the profile model
# ===========================================================================
# The whole file has run under --nogui to get here (that is the primary
# evidence). This adds a static one: not one of the new procs may name a Tk
# command, because src/ase.tcl is sourced at startup under --nogui and
# test_ase_core drives it true-headless. A missing proc lands in the same list,
# so the check cannot pass by finding nothing.
# RESTATED 2026-08-17: the blocklist was blind to most of Tk. MEASURED against
# the old alternation, `canvas .c -width 10`, `menu .m`, `listbox .l`, `text .t`,
# `scrollbar .s`, `menubutton .mb`, `destroy .sim`, `focus .sim` and `tk_dialog`
# ALL scored zero hits -- item 13 could have put a widget in one of these procs
# and this check would have stayed green, which is the whole thing it exists to
# stop. Two changes: comment lines are stripped first (prose is what forced the
# old list to stay narrow -- `raise`, `text` and `font` occur in English), and the
# regexp is driven against SENTINEL bodies as well, so a detector that stops
# detecting fails this check instead of silently passing everything.
proc strip_tcl_comments {body} {
  set out {}
  foreach line [split $body "\n"] {
    if {[regexp {^[ \t]*#} $line]} { continue }
    lappend out $line
  }
  return [join $out "\n"]
}
set tkre {(^|[^-a-zA-Z0-9_:.$])(ttk::[a-zA-Z_]*|tk_[a-zA-Z_]*|winfo|toplevel|image[ \t]+create|canvas|menubutton|menu|listbox|scrollbar|spinbox|panedwindow|labelframe|scale|text|message|pack|place|grid|frame|button|entry|label|checkbutton|radiobutton|destroy|focus|selection|clipboard|font|raise|lower|bell|tkwait|grab|wm|bind)([ \t\n]|$)}
set tk_blind {}
foreach s [list {canvas .c -width 10} {menu .m} {listbox .l} {text .t} \
                {scrollbar .s} {menubutton .mb} {destroy .sim} {focus .sim} \
                {tk_dialog .d t m {} 0 ok} {winfo exists .} {ttk::button .b} \
                {image create photo im} {wm title . x} {bind . <Key> {}} \
                {toplevel .t} {pack .b -side top} {grid .b -row 0} \
                {entry .e -textvariable v} {label .l -text x} {frame .f}] {
  if {![regexp $tkre $s]} { lappend tk_blind $s }
}
set tk_hits {}
foreach p {sim_profile_field_defaults sim_profile_fields sim_profile_field_default
           sim_casemode_valid sim_profile_valid sim_profile_normalize
           sim_profile_shape_stamp sim_profile_normalize_if_changed
           sim_profile_get sim_profile_set sim_profile_casemode
           sim_profile_detected sim_profile_supports sim_profile_selectable
           sim_profile_expand_vars
           sim_profile_exe_path sim_profile_probe_stale sim_profile_probe_record
           sim_profile_default_index sim_profile_row
           ase::backend_tool ase::sim_profile_resolve ase::sim_profile_casemode
           ase::sim_profile_stamp ase::sim_profile_clear} {
  if {[catch {info body $p} b]} { lappend tk_hits MISSING:$p ; continue }
  if {[regexp $tkre [strip_tcl_comments $b] -> _pre cmdname]} { lappend tk_hits $p:$cmdname }
}
eqcheck CS166-no-Tk-in-any-profile-proc-and-the-detector-can-see-Tk \
  "hits=<$tk_hits> blind=<$tk_blind>" "hits=<> blind=<>"

catch {test_scratch_drop $tmp}
puts "----"
puts "test_sim_profiles: $npass passed, $fail failed"
if {$fail == 0} { puts "RESULT: ALL PASS ($npass checks)" } else { puts "RESULT: $fail FAILED ($npass passed)" }
flush stdout
exit [expr {$fail == 0 ? 0 : 1}]
