/* This is a very mangled version of Vadc__main.cpp as generated by Verilator. */

// Verilated -*- C++ -*-
// DESCRIPTION: main() calling loop, created with Verilator --main

#include "verilated.h"
#include "Vlng.h"

#include "ngspice/cmtypes.h" // For Digital_t
#include "ngspice/cosim.h"   // For struct co_info and prototypes

/* ------------------------------------------------------------------------
 * XSCHEM LOCAL PATCH — VCD tracing of the co-simulated design's INTERNALS.
 *
 * Stock ngspice ships this file with no trace object at all, so `--trace`
 * produces nothing: only module PORTS ever cross the d_cosim boundary, and
 * ngspice's own raw file cannot hold event nodes in any case (measured; see
 * doc/claude/specs/mixed_signal_signal_browser.md M1/M6/M10). Internal Verilog
 * signals are therefore invisible to every consumer downstream.
 *
 * With VM_TRACE the model dumps its whole hierarchy to a VCD alongside the raw.
 * Output path comes from the .model card's `sim_args` (first element), so two
 * d_cosim instances in one deck do not overwrite each other:
 *
 *     .model counter d_cosim simulation="./counter.so" sim_args=["counter.vcd"]
 *
 * Build with tools/cosim/build_cosim_so.sh -V (adds --trace and links
 * verilated_vcd_c.o, which lives OUTSIDE Vlng__ALL.a).
 * ---------------------------------------------------------------------- */
#if VM_TRACE
#include "verilated_vcd_c.h"
#include <cmath>
#include <cstdint>
#include <cstdlib>

static VerilatedVcdC *ng_tracep     = NULL;
static double         ng_trace_tick = 1e-12; /* seconds per contextp time unit */
static uint64_t       ng_trace_last = 0;     /* dump() must never go backwards */
static unsigned       ng_trace_n    = 0;     /* dumps since the last flush */

/* ⚠ THE FILE IS TRUNCATED WITHOUT THIS. cosim.h says `cleanup` is called "just
 * before [the co-simulator] is unloaded at the end of a simulation run", but
 * ngspice-46 in batch mode does not reliably reach it: the first trace build of
 * tb_counter_wrapper ended with a half-written `#197` where `#1975796` belonged.
 * Flushing periodically bounds the loss, and atexit() closes the file properly
 * on any normal exit whether or not cleanup fires. */
#define NG_TRACE_FLUSH_EVERY 4096

static void ng_trace_close(void)
{
    if (ng_tracep) {
        ng_tracep->close();
        delete ng_tracep;
        ng_tracep = NULL;
    }
}

/* Dump the whole design at SPICE time `vtime` (seconds).
 *
 * ⚠ MONOTONICITY IS NOT OPTIONAL. With method == After_input ngspice calls
 * step() more than once at the SAME vtime (once per input change), and on a
 * rejected timestep it can even call with an EARLIER one (the condition behind
 * ngspice's "XSPICE time is behind vtime:" diagnostic). VerilatedVcdC requires
 * non-decreasing time, so clamp rather than trust the caller. */
static void ng_trace_dump(double vtime)
{
    uint64_t t;

    if (!ng_tracep)
        return;
    t = (uint64_t)(vtime / ng_trace_tick + 0.5);
    if (t < ng_trace_last)
        t = ng_trace_last;
    ng_trace_last = t;
    ng_tracep->dump(t);
    if (++ng_trace_n >= NG_TRACE_FLUSH_EVERY) {
        ng_trace_n = 0;
        ng_tracep->flush();
    }
}

static void ng_trace_cleanup(struct co_info *pinfo)
{
    (void)pinfo;
    ng_trace_close();
}
#else
#define ng_trace_dump(t) ((void)0)
#endif

//======================

/* Structure for the input table. */

struct input {
  const char   *name;
  unsigned int  offset;
  unsigned int  count;
};

/* This VL_DATA macro is used in header files inputs.h, outputs.h and inouts.h
 * to write functions accept_input() and step().
 * The macro is used several times with different definitions.
 */

/* Generate the previous values table used by step(). */

#define VL_DATA(size, name, msb, lsb) + msb - lsb + 1
static const unsigned int outs = 0
#include "outputs.h"
  ;
static const unsigned int inouts = 0
#include "inouts.h"
  ;

static unsigned char previous_output[outs + inouts];

#undef VL_DATA

/* The input function: it should ignore out-of-range values of index. */

#define VL_DATA(size, name, msb, lsb)      \
  if (index >= msb - lsb + 1) {            \
    index -= msb - lsb + 1;                \
  } else if (msb == 0 && lsb == 0) {       \
    topp->name = val ? 1 : 0;              \
    return;                                \
  } else {                                 \
    if (val)                               \
      topp->name |= (1 << (msb - index));  \
    else                                   \
      topp->name &= ~(1 << (msb - index)); \
    return;                                \
  }

static void accept_input(struct co_info *pinfo,
			 unsigned int index, Digital_t *vp)
{
    Vlng          *topp = (Vlng *)pinfo->handle;
    unsigned int   val, offset;

    val = vp->state;
    if (val == UNKNOWN)
        return;    // Verilator simulations are two-state.

#include "inputs.h"

    /* For inout ports the new value must be stored to detect changes. */

    offset = outs;
#undef VL_DATA
#define VL_DATA(size, name, msb, lsb)       \
  if (index >= msb - lsb + 1) {             \
    index -= msb - lsb + 1;                 \
    offset += msb - lsb + 1;                \
  } else if (msb == 0 && lsb == 0) {        \
    topp->name = val ? 1 : 0;               \
    previous_output[index + offset] = val;  \
    return;                                 \
  } else {                                  \
    if (val) 			 	    \
      topp->name | (1 << (msb - index));    \
    else                                    \
      topp->name &= ~(1 << (msb - index));  \
    previous_output[index + offset] = val;  \
    return;                                 \
  }

#include "inouts.h"
}
#undef VL_DATA

/* The step function that calls the Verilator code. */

#ifndef WITH_TIMING
/* The simple case is when the Verilog source contained no time delays,
 * or was compiled with compiled with --no-timing.
 */

#define VL_DATA(size, name, msb, lsb)        \
  for (i = msb; i >= lsb; --i) {             \
    if (topp->name & (1 << i))               \
      bit = 1;                               \
    else                                     \
      bit = 0;                               \
    if (bit ^ previous_output[index]) {      \
      previous_output[index] = bit;          \
      oval.state = (Digital_State_t)bit;     \
      (*pinfo->out_fn)(pinfo, index, &oval); \
    }                                        \
    ++index;                                 \
  }

static void step(struct co_info *pinfo)
{
    static Digital_t  oval = {ZERO, STRONG};
    Vlng             *topp;
    int               index, i;
    unsigned char     bit;

    topp = (Vlng *)pinfo->handle;
    topp->eval();
    ng_trace_dump(pinfo->vtime); /* XSCHEM PATCH: after eval, before out_fn */

    /* Now scan the outputs for changes. */

    index = 0;
#include "outputs.h"
#include "inouts.h"
}

#else /* WITH_TIMING */

#define VL_DATA(size, name, msb, lsb)        \
  for (i = msb; i >= lsb; --i) {             \
    if (topp->name & (1 << i))               \
      bit = 1;                               \
    else                                     \
      bit = 0;                               \
    if (bit ^ previous_output[index]) {      \
      stop = 1;                              \
      previous_output[index] = bit;          \
      oval.state = (Digital_State_t)bit;     \
      (*pinfo->out_fn)(pinfo, index, &oval); \
    }                                        \
    ++index;                                 \
  }

static void step(struct co_info *pinfo)
{
    static Digital_t  oval = {ZERO, STRONG};
    VerilatedContext *contextp;
    Vlng             *topp;
    double            tick;
    uint64_t          target, next;
    int               index, i, stop = 0;
    unsigned char     bit;

    /* When Verilog source was compiled with --timing, run queued evants
     * until the Verilog simulation catches up with SPICE.
     */

    topp = (Vlng *)pinfo->handle;
    contextp = topp->contextp();
    tick = pow(10, contextp->timeprecision());
    target = pinfo->vtime / tick;

    /* Step the Verilog simulation towards the target time. */

    do {
      if (topp->eventsPending())
	next = topp->nextTimeSlot();
      else
	next = target;
      if (next >= target) {
	stop = 1;
	next = target;
      }
      contextp->time(next);
      topp->eval();
      /* XSCHEM PATCH: dump at the Verilog event time, not the SPICE target —
       * a --timing design can fire several internal events inside one SPICE
       * timestep, and dumping only at `target` would collapse them all. */
      ng_trace_dump(next * tick);

      /* Scan for output and stop early if found. */

      index = 0;
#include "outputs.h"
#include "inouts.h"
    } while (!stop);

    /* Update the shared simulation time on early exit. */

    if (next < target)
      pinfo->vtime = next * tick;
}

#endif /* WITH_TIMING */
#undef VL_DATA

extern "C" void Cosim_setup(struct co_info *pinfo)
{
    int i;

    // Setup context, and defaults

    Verilated::debug(0);
    std::unique_ptr<VerilatedContext> contextp{new VerilatedContext};

    // Construct the Verilated model, from Vtop.h generated from Verilating

#if VM_TRACE
    Verilated::traceEverOn(true);  /* must precede trace(), which precedes eval */
#endif
    Vlng *topp{new Vlng{contextp.get()}};

    /* XSCHEM PATCH — LIFETIME. Upstream declares contextp `const
     * std::unique_ptr` and lets it die at the end of this function while topp
     * keeps a raw pointer to it. Release ownership so the context outlives the
     * function, i.e. lasts as long as the process.
     *
     * WHO ACTUALLY NEEDS THIS. An earlier version of this comment answered
     * "the trace setup, which needs the context too". That is FALSE, and the
     * check takes a minute: the local `ctx` below is used at exactly two places
     * — the ng_trace_tick assignment and the non-VM_TRACE (void) cast — and
     * both are inside Cosim_setup, above its closing brace, where the
     * unique_ptr is still alive. contextp.get() would have served the tracer
     * identically.
     *
     * But grepping for `ctx` is NOT the same question as "who reaches the
     * context". Two ALIASES of the same object outlive this function, neither
     * of them spelled `ctx`, and BOTH are dereferenced after it returns:
     *
     *   1. topp->contextp() — the raw pointer the model kept. The WITH_TIMING
     *      step() above calls timeprecision() and time() through it. That is
     *      the use-after-free of spec M15. Compiled only with -t.
     *
     *   2. Verilated::threadContextp() — a thread-local that the
     *      VerilatedContext CONSTRUCTOR points at itself and that its
     *      DESTRUCTOR never clears (verilated.cpp:2421 and :2434 in the
     *      installed Verilator 5.020), so it keeps handing out the dead
     *      pointer. This one is reached from the GENERATED model during
     *      topp->eval(), in EVERY build, -t or not, whenever the user's Verilog
     *      contains $time, $display with %t, $finish, $stop or $fatal:
     *      VL_TIME_Q() expands to Verilated::threadContextp()->time()
     *      (verilated_funcs.h:302) and vl_finish() calls gotFinish() on the
     *      same pointer (verilated.cpp:113).
     *
     * So this release is LOAD-BEARING IN EVERY BUILD, not only under -t, and it
     * is NOT "inert in the shipping configuration" — an earlier version of this
     * comment said that too, and it was also wrong. Measured 2026-08-10 with
     * the release neutered and no -t anywhere: a counter whose always-block
     * does $display("t=%t", $time) faults under AddressSanitizer with
     * heap-use-after-free in VerilatedContext::time(), called from
     * Vlng___024root___nba_sequent__TOP__0 under Vlng::eval_step(), on memory
     * freed at the end of the Cosim_setup analogue.
     *
     * The older "byte-identical VCD, clean valgrind" measurement is real but
     * NARROW, and that is the whole trap: it was taken on the reference design
     * xschem_library/ngspice_verilog_cosim/counter.v, whose only $display has
     * no %t and which never calls $finish, so it touches neither alias. The
     * same neutered harness on that file is ASan-clean; on the %t version it is
     * not. Do not re-derive "inert" from a run of counter.v.
     *
     * The leak is deliberate and bounded: one VerilatedContext, never freed,
     * once per process. d_cosim unloads the whole library at end of run. See
     * doc/claude/specs/mixed_signal_signal_browser.md §A, "The shipped cosim
     * build, precisely". */
    VerilatedContext *ctx = contextp.release();

    /* Return information to caller. */

    pinfo->handle = topp;
    pinfo->step = step;

#if VM_TRACE
    /* Trace target: first sim_args element, else a default beside the deck. */
    {
        const char *vcd = (pinfo->sim_argc > 0 && pinfo->sim_argv[0] &&
                           pinfo->sim_argv[0][0])
                            ? pinfo->sim_argv[0] : "cosim.vcd";

        ng_trace_tick = pow(10, ctx->timeprecision());
        ng_trace_last = 0;
        ng_trace_n = 0;
        ng_tracep = new VerilatedVcdC;
        topp->trace(ng_tracep, 99);   /* 99 = full hierarchy depth */
        ng_tracep->open(vcd);
        pinfo->cleanup = ng_trace_cleanup;
        std::atexit(ng_trace_close);  /* cleanup is not reliably reached */
    }
#else
    (void)ctx;
#endif

#define VL_DATA(size, name, msb, lsb) i += msb - lsb + 1; // Count ports

    i = 0;
#include "inputs.h"
    pinfo->in_count = i;

    pinfo->out_count = outs;
    pinfo->inout_count = inouts;
    pinfo->in_fn = accept_input;
#ifdef WITH_TIMING
    pinfo->method = Both;         // There may be immediate results from input.
#else
    pinfo->method = After_input;  // Verilator requires input to advance.
#endif
}
#undef VL_DATA
