# Delta-sweep DRIVER -- hardening sprint Track C, step C3.
# Spec: doc/claude/suggestions/hardening_sprint_plan.md (C3); WIRING.md §12 (fuzzer process).
#
# Sweeps each fixture x gesture x a delta grid, runs the C2 assertion pack on every drop, and
# for every non-GREEN, non-REFUSED drop (a saved RED corruption or an AMBER route regression)
# writes a SELF-CONTAINED replayable RED test file -- failures auto-become regression skeletons.
# Prints a summary matrix. TRUE HEADLESS, no X.
#
# Config via env (the nightly CI shards by fixture -- C5):
#   FUZZ_FIXTURES  space list, default "before_3 before_5 before_7 before_8"
#   FUZZ_GESTURES  space list, default "stretch rot rot2 flip split"
#   FUZZ_OUTDIR    replay-file dir, default <this dir>/fails
#   FUZZ_TARGET    dragged instance, default R18 (every fixture's 2-pin res)
#   FUZZ_MAXFAIL   cap on replay files PER (fixture,gesture,verdict), default 40 (0 = no cap)
#   FUZZ_DENSE     "1" = full grid; "0"/unset uses the near/far strided grid (default)
#   FUZZ_ENFORCE   B3 enforcement, default 1; 0 = log-only (a would-be-REFUSED short SAVES ->
#                  the sweep sees it as RED -- fuzzes the raw router, the cheapest "revert B3")
#
# Gesture menu (plan: {plain drag, m-stretch, m+ALT-R, m+ALT-R x2, m+ALT-F, split}). In
# cadence_compat plain-LMB == 'm' (WIRING.md §2.1), so plain and m-stretch are the one
# `stretch` type -> five distinct scripted gestures.
#
# Run:  src/xschem --nogui --pipe -q --nolog --script tests/headless/fuzz/fuzz_sweep.tcl
source [file join [file dirname [info script]] harness.tcl]

proc envdef {name def} { expr {[info exists ::env($name)] && $::env($name) ne "" ? $::env($name) : $def} }

set FIXTURES [envdef FUZZ_FIXTURES {before_3 before_5 before_7 before_8}]
set GESTURES [envdef FUZZ_GESTURES {stretch rot rot2 flip split}]
set OUTDIR   [envdef FUZZ_OUTDIR [file join [file dirname [info script]] fails]]
set TARGET   [envdef FUZZ_TARGET R18]
set MAXFAIL  [envdef FUZZ_MAXFAIL 40]
set DENSE    [envdef FUZZ_DENSE 0]
set ::fuzz_enforce [envdef FUZZ_ENFORCE 1]   ;# read by harness fuzz_gates per drop

# Delta grid: cadsnap(10) * index, index in [-15..15], stride 1 near zero (|idx|<=5), stride 3
# farther out -- dense where the historical bugs cluster (small deltas onto adjacent copper),
# sparse in the far field. FUZZ_DENSE=1 uses every index.
proc fuzz_grid {dense} {
  set idx {}
  if {$dense} {
    for {set i -15} {$i <= 15} {incr i} { lappend idx $i }
  } else {
    for {set i -5} {$i <= 5} {incr i} { lappend idx $i }
    foreach i {6 9 12 15} { lappend idx $i [expr {-$i}] }
  }
  set out {}
  foreach i [lsort -integer -unique $idx] { lappend out [expr {$i * 10}] }
  return $out
}

file mkdir $OUTDIR

# A self-contained replay file: re-runs the exact drop and RESULT: passes only once it is
# GREEN -- i.e. it is a failing (RED/AMBER) regression test until the bug is fixed. The literal
# body is written with single-line brace blocks so the replay's own $/[...] are NOT interpolated
# at generation time (only the spec line is).
proc write_replay {outdir fixture gesture verdict fails} {
  set tag [fuzz_tag $fixture $gesture]
  set path [file join $outdir "fuzz_fail_$tag.tcl"]
  set spec [fuzz_spec_line $fixture $gesture]
  set fh [open $path w]
  puts $fh "# AUTO-GENERATED by fuzz_sweep.tcl (Track C / C3): a failing regression skeleton."
  puts $fh "# Currently $verdict (fails: $fails). Goes RESULT: ALL PASS only once the drop is GREEN."
  puts $fh "#   src/xschem --nogui --pipe -q --nolog --script [file tail $path]"
  puts $fh {set _here [file dirname [file normalize [info script]]]}
  puts $fh {set _h ""}
  puts $fh {foreach _c [list [file join $_here harness.tcl] [file join $_here .. harness.tcl]] {if {[file exists $_c]} {set _h $_c; break}}}
  puts $fh {if {$_h eq ""} {puts "RESULT: 1 FAILED (cannot locate harness.tcl)"; exit 1}}
  puts $fh {source $_h}
  puts $fh "set ::fuzz_enforce $::fuzz_enforce   ;# reproduce the sweep's B3 mode (else an enforce-off RED replays as REFUSED)"
  puts $fh "set d \[$spec\]"
  puts $fh {puts "verdict=[dict get $d verdict] landed=[dict get $d landed] fails=[dict get $d fails]"}
  puts $fh {puts "checks: [dict get $d checks]"}
  puts $fh {if {[dict get $d verdict] eq "GREEN"} {puts "RESULT: ALL PASS (drop now routes clean)"; exit 0} else {puts "RESULT: 1 FAILED ([dict get $d verdict]: [dict get $d fails])"; exit 1}}
  close $fh
  return $path
}

# ---- run the sweep --------------------------------------------------------
set grid [fuzz_grid $DENSE]
puts "fuzz_sweep: fixtures={$FIXTURES} gestures={$GESTURES} grid=[llength $grid]^2 target=$TARGET enforce=$::fuzz_enforce outdir=$OUTDIR"
puts [format "%-9s %-8s | %6s %6s %6s %6s | %s" fixture gesture GREEN AMBER RED REFUSED replays]

set gtot 0; set atot 0; set rtot 0; set ftot 0; set nrep 0
foreach fx $FIXTURES {
  foreach g $GESTURES {
    array set cnt {GREEN 0 AMBER 0 RED 0 REFUSED 0}
    array set capped {AMBER 0 RED 0}
    foreach dx $grid {
      foreach dy $grid {
        if {$dx == 0 && $dy == 0} continue
        set gesture [list target $TARGET type $g dx $dx dy $dy]
        set d [fuzz_drop $fx $gesture]
        set v [dict get $d verdict]
        incr cnt($v)
        if {$v eq "RED" || $v eq "AMBER"} {
          if {$MAXFAIL == 0 || $cnt($v) <= $MAXFAIL} {
            write_replay $OUTDIR $fx $gesture $v [dict get $d fails]; incr nrep
          } else { incr capped($v) }
        }
      }
    }
    set capnote ""
    if {$capped(RED) || $capped(AMBER)} { set capnote " (capped: +$capped(RED) RED, +$capped(AMBER) AMBER not written)" }
    puts [format "%-9s %-8s | %6d %6d %6d %6d |%s" \
      $fx $g $cnt(GREEN) $cnt(AMBER) $cnt(RED) $cnt(REFUSED) $capnote]
    incr gtot $cnt(GREEN); incr atot $cnt(AMBER); incr rtot $cnt(RED); incr ftot $cnt(REFUSED)
  }
}
puts [format "%-9s %-8s | %6d %6d %6d %6d | %d replay files -> %s" TOTAL "" $gtot $atot $rtot $ftot $nrep $OUTDIR]
puts "RESULT: [expr {$rtot+$atot}] non-clean drops ($rtot RED + $atot AMBER); $ftot refused; $gtot green"
